#!/bin/bash
#SBATCH -N <NODES>
#SBATCH -n <TASKS>
#SBATCH -c 1
#SBATCH -q regular
#SBATCH -t <TIME>
#SBATCH --constraint=cpu
#SBATCH --output=output/slurm/job_%j.out
#SBATCH --error=output/slurm/job_%j.err

#This configuration is for perlmutter

HPL="<HPL_LOCATION>"
ROOT="<ROOT>"
OUTPUT=$ROOT/output

FILENAME="HPL_RUN"
DESCRIPTION="$FILENAME, <DESCRIPTION>"

echo "$SLURM_JOB_ID : $DESCRIPTION" >> $OUTPUT/descriptions.txt

OUTDIR=$OUTPUT/$FILENAME
mkdir -p $OUTDIR

cd $(dirname $HPL)
srun xhpl | tee $OUTDIR/hpl_$SLURM_JOB_ID.out








