#!/bin/bash
#SBATCH -N <NODES>
#SBATCH -n <TASKS>
#SBATCH -c 1
#SBACTH -C cpu
#SBATCH -t 30:00
#SBATCH --output=output/slurm/job_%j.out
#SBATCH --error=output/slurm/job_%j.err

#This configuration is for perlmutter

HPL="<HPL_LOCATION>"
ROOT="<ROOT>"
OUTPUT=$ROOT/output

FILENAME="HPL_RUN"
DESCRIPTION="$FILENAME, <DESCRIPTION>"

echo "$SLURM_JOB_ID : $DESCRIPTION" >> $OUTPUT/descriptions.txt

OUTDIR=$OUTPUT/$FILENAME
mkdir -p $OUTDIR

srun $HPL | tee $OUTDIR/hpl_$SLURM_JOB_ID.out








